namespace Center.Server
{
    public enum ePackageType
    {
        RSAKey = 0,
        LOGIN = 1,
        KITOFF_USER = 2,
        ALLOW_USER_LOGIN = 3,
        USER_OFFLINE = 4,
        USER_ONLINE = 5,
        USER_STATE = 6,
        UPDATE_ASS = 7,
        UPDATE_CONFIG_STATE = 8,
        CHARGE_MONEY = 9,
        SYS_NOTICE = 10,
        SYS_CMD = 11,
        PING = 12,
        UPDATE_PLAYER_MARRIED_STATE = 13,
        MARRY_ROOM_INFO_TO_PLAYER = 14,
        SHUTDOWN = 15,
        SCENE_CHAT = 19,
        CHAT_PERSONAL = 37,
        SYS_MESS = 38,
        B_BUGLE = 72,
        MAIL_RESPONSE = 117,
        MESSAGE = 118,
        DISPATCHES = 123,
        CONSORTIA_RESPONSE = 128,
        CONSORTIA_CREATE = 130,
        CONSORTIA_DELETE = 131,
        CONSORTIA_ALLY_ADD = 147,
        CONSORTIA_CHAT = 155,
        CONSORTIA_OFFER = 156,
        CONSORTIA_RICHES = 157,
        CONSORTIA_FIGHT = 158,
        CONSORTIA_UPGRADE = 159,
        FRIEND_STATE = 165,
        FRIEND_RESPONSE = 166,
        Rate = 177,
        MACRO_DROP = 178,
        IP_PORT = 240,
        MARRY_ROOM_DISPOSE = 241,
        KIT_OFF_PLAYER = 242,
    }
}
