using System;
namespace Game.Server.Packets
{
	public enum ConsortiaPackageType
	{
		CONSORTIA_TRYIN,
		CONSORTIA_CREATE,
		CONSORTIA_DISBAND,
		CONSORTIA_RENEGADE,
		CONSORTIA_TRYIN_PASS,
		CONSORTIA_TRYIN_DEL,
		CONSORTIA_RICHES_OFFER,
		CONSORTIA_APPLY_STATE,
		CONSORTIA_DUTY_DELETE = 9,
		CONSORTIA_DUTY_UPDATE,
		CONSORTIA_INVITE,
		CONSORTIA_INVITE_PASS,
		CONSORTIA_INVITE_DELETE,
		CONSORTIA_DESCRIPTION_UPDATE,
		CONSORTIA_PLACARD_UPDATE,
		CONSORTIA_BANCHAT_UPDATE,
		CONSORTIA_USER_REMARK_UPDATE,
		CONSORTIA_USER_GRADE_UPDATE,
		CONSORTIA_CHAIRMAN_CHAHGE,
		CONSORTIA_CHAT,
		CONSORTIA_LEVEL_UP,
		CONSORTIA_TASK_RELEASE,
		DONATE,
		CONSORTIA_EQUIP_CONTROL,
		POLL_CANDIDATE,
		SKILL_SOCKET,
		CONSORTION_MAIL = 29,
		BUY_BADGE = 28,
		BOSS_OPEN_CLOSE = 31,
		CONSORTIA_BOSS_INFO = 30
	}
}
